title: Wildly Inaccurate
description: >
  A collection of guides &amp; opinions about programming and the state of the web, from a developer at BBC News.

url: https://wildlyinaccurate.com
permalink: /:title/

category_dir: category
tag_dir: tag

excerpt_separator: <!--more-->
paginate: 15

email: joseph@wildlyinaccurate.com
twitter_username: joseph_wynn
github_username:  wildlyinaccurate

gems:
  - jekyll-responsive-image
  - jekyll-paginate
  - jekyll-last-modified-at

responsive_image:
  default_quality: 75
  template: _includes/thumbnail.html
  output_path_format: assets/r/%{width}/%{basename}
  sizes:
    # Device widths for full-width images
    - width: 320
      quality: 60
      progressive: true

    - width: 380
      quality: 60
      progressive: true

    - width: 420
      quality: 60
      progressive: true

    - width: 640
      progressive: true

    - width: 768
      progressive: true

    - width: 1024
      progressive: true

    - width: 1280
      progressive: true

    - width: 1366
      progressive: true

    - width: 1440
      progressive: true

    - width: 1680
      progressive: true

    # Breakpoint sizes for inline images
    - width: 510
      progressive: true

    - width: 690
      progressive: true

    - width: 930
      progressive: true

    - width: 1110
      progressive: true

markdown: kramdown
highlighter: rouge
kramdown:
  toc_levels: 1..3
  input: GFM

include:
  - search.json

exclude:
  - README.md
  - bower_components
  - bower.js
  - Gemfile
  - Gemfile.lock
  - Gruntfile.js
  - node_modules
  - package.json
  - elm
  - elm-stuff
