title: Wildly Inaccurate
description: >
  Guides &amp; opinions about programming and the state of the web.

url: https://wildlyinaccurate.com
permalink: /:title

excerpt_separator: <!--more-->

email: joseph@wildlyinaccurate.com
twitter_username: Joseph_Wynn
github_username:  wildlyinaccurate

gems: [jekyll/responsive_image]

responsive_image:
  template: _includes/thumbnail.html
  sizes:
    # 320px devices
    - width: 290

    # 360px devices
    - width: 315

    # Container width on S devices
    - width: 720

    # Container width on M devices
    - width: 940

    # Container width on L devices
    - width: 1140

    # Common device widths (minus ~80px allowance for UI) for full-width images
    - width: 1280
    - width: 1360
    - width: 1680
    - width: 1840


markdown: kramdown

sass:
    style: compressed
