title: Wildly Inaccurate
description: >
  A collection of guides &amp; opinions about programming and the state of the web, from a developer at BBC News.

url: https://wildlyinaccurate.com
permalink: /:title/
category_dir: category

excerpt_separator: <!--more-->
paginate: 15

email: joseph@wildlyinaccurate.com
twitter_username: Joseph_Wynn
github_username:  wildlyinaccurate

gems: [jekyll/responsive_image]

responsive_image:
  template: _includes/thumbnail.html
  sizes:
    # 320px devices
    - width: 290

    # 360px devices
    - width: 315

    # Container width on S devices
    - width: 720

    # Container width on M devices
    - width: 940

    # Container width on L devices (yes, this is smaller than M)
    - width: 780

    # Common device widths (minus ~80px allowance for UI) for full-width images
    - width: 1280
    - width: 1360
    - width: 1680
    - width: 1840

markdown: KramdownPygments

kramdown:
    toc_levels: 1..3
    input: GFM

exclude:
    - bower_components
    - bower.js
    - Gemfile
    - Gemfile.lock
    - Gruntfile.js
    - node_modules
    - package.json
